---
# File: main.yml
# Part: Varnish
#
# Description:
# - Install latest Varnish from Varnish-Cache.org
#
# Parameters:
#
# Dependencies ([part:]type:filename):
#
# OS familly: Ubuntu >= 12.04

- name: Varnish | Fetch signing key
  apt_key: url=http://repo.varnish-cache.org/debian/GPG-key.txt state=present
  when_string: ${ansible_lsb.release} != "13.04"

- name: Varnish | Add Varnish repository
  apt_repository: repo="http://repo.varnish-cache.org/ubuntu/ ${ansible_lsb.codename} varnish-3.0"
  when_string: ${ansible_lsb.release} != "13.04"

- name: Varnish | Install Varnish package 
  apt: pkg=varnish state=present update_cache=yes

- name: Varnish | Push default configuration template
  template:
    src=$repository_basedir/varnish/templates/varnish.default.j2
    dest=/etc/default/varnish
    owner=root group=root mode=0644
  notify:
  - varnish-restart

# Insure service is running.
- name: Varnish | Insure deamon is running correctly
  service: name=varnish state=started

