---

- hosts: webservers
  user: vagrant
  sudo: True

  vars:
    repository_basedir: ..
    bootstrap_upgrade: True
    ansible_repodir: /opt/ansible-repository

  tasks:
    # Update APT Caches and make sure base packages are installed
    - include: $repository_basedir/bootstrap/tasks/setup.yml

    # Install Python packages
    - include: $repository_basedir/python/tasks/setup.yml

    # Install Ansible
    - include: $repository_basedir/ansible/tasks/setup.yml
